#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.
i = 1
o = 0
n = 0
fib_list = []
list = []
while i<4000000:
    n = o+i
    o = i
    i = n
    print(i,n)
    print(fib_list)
    if i%2==0:
        list.append(i)
print(list)
print(sum(list))
        
